export const HaitiCities: string[] = [
    "Dessalines",
    "Desdunes",
    "Grande-Saline",
    "Petite Rivière de l'Artibonite",
    "Gonaïves",
    "Ennery",
    "L'Estère",
    "Gros-Morne",
    "Anse-Rouge",
    "Terre-Neuve",
    "Marmelade",
    "Saint-Michel-de-l'Atalaye",
    "Saint-Marc",
    "Les Arcadins",
    "La Chapelle",
    "Liancourt",
    "Verrettes",
    "Montrouis",
    "Cerca-la-Source",
    "Thomassique",
    "Hinche",
    "Cerca-Carvajal",
    "Maïssade",
    "Thomonde",
    "Lascahobas",
    "Baptiste",
    "Belladère",
    "Savanette",
    "Mirebalais",
    "Boucan-Carré",
    "Saut-d'Eau",
    "Anse-d'Hainault",
    "Dame-Marie",
    "Les Irois",
    "Beaumont",
    "Corail",
    "Pestel",
    "Roseaux",
    "Jérémie",
    "Abricots",
    "Bonbon",
    "Chambellan",
    "Marfranc",
    "Moron",
    "Anse-à-Veau",
    "Arnaud",
    "L'Asile",
    "Petit-Trou-de-Nippes",
    "Plaisance-du-Sud",
    "Baradères",
    "Grand-Boucan",
    "Miragoâne",
    "Fonds-des-Nègres",
    "Paillant",
    "Petite-Rivière-de-Nippes",
    "Acul-du-Nord",
    "Milot",
    "Plaine-du-Nord",
    "Borgne",
    "Port-Margot",
    "Cap-Haïtien",
    "Limonade",
    "Quartier-Morin",
    "Grande-Rivière-du-Nord",
    "Bahon",
    "Limbé",
    "Bas-Limbé",
    "Plaisance",
    "Pilate",
    "Saint-Raphaël",
    "Dondon",
    "La Victoire",
    "Pignon",
    "Ranquitte",
    "Fort-Liberté",
    "Perches",
    "Ferrier",
    "Ouanaminthe",
    "Capotille",
    "Mont-Organisé",
    "Trou-du-Nord",
    "Caracol",
    "Sainte-Suzanne",
    "Grand-Bassin",
    "Terrier-Rouge",
    "Vallières",
    "Carice",
    "Mombin-Crochu",
    "Môle-Saint-Nicolas",
    "Baie-de-Henne",
    "Bombardopolis",
    "Jean-Rabel",
    "Port-de-Paix",
    "Bassin-Bleu",
    "Chansolme",
    "Lapointe",
    "La Tortue",
    "Saint-Louis-du-Nord",
    "Anse-à-Foleur",
    "Arcahaie",
    "Cabaret",
    "Croix-des-Bouquets",
    "Cornillon",
    "Fonds-Verrettes",
    "Ganthier",
    "Thomazeau",
    "Anse-à-Galets",
    "Pointe-à-Raquette",
    "Léogâne",
    "Grand-Goâve",
    "Petit-Goâve",
    "Port-au-Prince",
    "Carrefour",
    "Cité Soleil",
    "Delmas",
    "Gressier",
    "Kenscoff",
    "Pétion-Ville",
    "Tabarre",
    "Aquin",
    "Cavaillon",
    "Saint-Louis-du-Sud",
    "Fond des Blancs",
    "Les Cayes",
    "Camp-Perrin",
    "Chantal",
    "Île-à-Vache",
    "Maniche",
    "Torbeck",
    "Chardonnières",
    "Les Anglais",
    "Tiburon",
    "Côteaux",
    "Port-à-Piment",
    "Roche-à-Bateaux",
    "Port-Salut",
    "Arniquet",
    "Saint-Jean-du-Sud",
    "Bainet",
    "Côtes-de-Fer",
    "Belle-Anse",
    "Anse-à-Pitres",
    "Grand-Gosier",
    "Thiotte",
    "Jacmel",
    "Cayes-Jacmel",
    "La Vallée",
    "Marigot"
];

export const convertToSelectOptions = (items: string[]) => {
  return items.map((city) => ({
    value: city,
    label: city,
  }))
}


export const HaitiState: string[] = [
  "Artibonite",
  "Centre",
  "Grand'Anse",
  "Nippes",
  "Nord",
  "Nord-Est",
  "Nord-Ouest",
  "Ouest",
  "Sud",
  "Sud-Est"
];




export const EmploymentDomains: string[] = [
  "Administration",
  "Agriculture",
  "Architecture",
  "Art et Design",
  "Automobile",
  "Banque et Finance",
  "Bâtiment et Travaux Publics",
  "Commerce",
  "Communication",
  "Comptabilité",
  "Construction",
  "Consulting",
  "Droit et Légal",
  "Éducation",
  "Énergie et Mines",
  "Environnement",
  "Hôtellerie et Restauration",
  "Immobilier",
  "Industrie",
  "Informatique et IT",
  "Ingénierie",
  "Logistique et Transport",
  "Management",
  "Marketing",
  "Médias",
  "Médical et Santé",
  "Mode et Beauté",
  "Pharmaceutique",
  "Ressources Humaines",
  "Recherche et Développement",
  "Sécurité",
  "Services Client",
  "Sports et Loisirs",
  "Télécommunications",
  "Tourisme",
  "Traduction et Interprétation",
  "Vente",
];
