export const HaitiCities: string[] = [
  "Port-au-Prince",
  "Cap-Haïtien",
  "Gonaïves",
  "Les Cayes",
  "Saint-Marc",
  "Jacmel",
  "Hinche",
  "Jérémie",
  "Miragoâne",
  "Petit-Goâve",
  "Port-de-Paix",
  "Aquin",
  "Fort-Liberté",
  "Ouanaminthe",
  "Léogâne",
  "Arcahaie",
  "Kenscoff",
  "Carrefour",
  "Delmas",
  "Cité Soleil",
  "Pétion-Ville",
  "Croix-des-Bouquets",
  "Thomazeau",
  "Verrettes",
  "Lascahobas",
  "Belladère",
  "Grand-Goâve",
  "Gros-Morne",
  "Marmelade",
  "Trou-du-Nord",
  "Anse-à-Galets",
  "Anse-à-Veau",
  "Cavaillon",
  "Chardonnieres",
  "Coteaux",
  "Dame-Marie",
  "Dessalines",
  "Fond-des-Nègres",
  "Ganthier",
  "Limbé",
  "Mirebalais",
  "Plaisance",
  "Port-Salut",
  "Saint-Louis-du-Sud",
  "Saint-Raphaël",
  "Thomonde",
  "Torbeck",
  "Vallières",
  "Île-à-Vache",
  "La Vallée-de-Jacmel",
  "Cornillon",
  "Fonds-Verrettes",
  "Baradères",
  "Chantal",
  "Île de la Tortue"
];

export const convertToSelectOptions = (items: string[]) => {
  return items.map((city) => ({
    value: city,
    label: city,
  }))
}


export const HaitiState: string[] = [
  "Artibonite",
  "Centre",
  "Grand'Anse",
  "Nippes",
  "Nord",
  "Nord-Est",
  "Nord-Ouest",
  "Ouest",
  "Sud",
  "Sud-Est"
];




export const EmploymentDomains: string[] = [
  "Administration",
  "Agriculture",
  "Architecture",
  "Art et Design",
  "Automobile",
  "Banque et Finance",
  "Bâtiment et Travaux Publics",
  "Commerce",
  "Communication",
  "Comptabilité",
  "Construction",
  "Consulting",
  "Droit et Légal",
  "Éducation",
  "Énergie et Mines",
  "Environnement",
  "Hôtellerie et Restauration",
  "Immobilier",
  "Industrie",
  "Informatique et IT",
  "Ingénierie",
  "Logistique et Transport",
  "Management",
  "Marketing",
  "Médias",
  "Médical et Santé",
  "Mode et Beauté",
  "Pharmaceutique",
  "Ressources Humaines",
  "Recherche et Développement",
  "Sécurité",
  "Services Client",
  "Sports et Loisirs",
  "Télécommunications",
  "Tourisme",
  "Traduction et Interprétation",
  "Vente",
];
