import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'bankMenu',
        path: '',
        title: 'Banks',
        translateKey: 'nav.bankMenu.bank',
        icon: 'bankMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'bankMenu.add',
                path: '/bank/add',
                title: 'Ajouter Bank',
                translateKey: 'nav.bankMenu.add',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'bankMenu.show',
                path: '/bank/show',
                title: 'Mes Banks',
                translateKey: 'nav.bankMenu.show',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            
            {
                key: 'bankMenu.current',
                path: '/bank/approval',
                title: 'Banks Encours',
                translateKey: 'nav.bankMenu.current',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
            {
                key: 'bankMenu.approved',
                path: '/bank/BankByStep/needApprobation',
                title: 'Banks Approuvées',
                translateKey: 'nav.bankMenu.approved',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
            {
                key: 'bankMenu.contrat',
                path: '/bank/BankByStep/needContract',
                title: 'Banks de contrats',
                translateKey: 'nav.bankMenu.contrat',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
            {
                key: 'bankMenu.renovation',
                path: '/bank/BankByStep/needRenovation',
                title: 'Banks renovation',
                translateKey: 'nav.bankMenu.renovation',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
            {
                key: 'bankMenu.ready',
                path: '/bank/BankByStep/readyToUse',
                title: 'Banks Terminées',
                translateKey: 'nav.bankMenu.ready',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
            {
                key: 'bankMenu.rejected',
                path: '/bank/BankByStep/rejected',
                title: 'Banks Rejectées',
                translateKey: 'nav.bankMenu.rejected',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
            {
                key: 'bankMenu.pending',
                path: '/bank/BankByStep/pending',
                title: 'Banks en Attente',
                translateKey: 'nav.bankMenu.pending',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
        ],
    },
    {
        key: 'proprioMenu',
        path: '',
        title: 'Landlord',
        translateKey: 'nav.proprioMenu.proprio',
        icon: 'proprioMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'proprioMenu.add',
                path: '/proprio/add',
                title: 'Add Landlord',
                translateKey: 'nav.proprioMenu.add',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'proprioMenu.myEntity',
                path: '/proprio/myEntity',
                title: 'Mes Entités',
                translateKey: 'nav.proprioMenu.myEntity',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'proprioMenu.show',
                path: '/proprio/show',
                title: 'Entité',
                translateKey: 'nav.proprioMenu.show',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
        ],
    },
    {
        key: 'configMenu',
        path: '',
        title: 'Configuration',
        translateKey: 'nav.configMenu.config',
        icon: 'configMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'configMenu.profil',
                path: '/proprio/add',
                title: 'Add Landlord',
                translateKey: 'nav.configMenu.profil',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'configMenu.password',
                path: '/proprio/show',
                title: 'Mot de Passe',
                translateKey: 'nav.configMenu.password',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
