import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Home',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'bankMenu',
        path: '',
        title: 'Banks',
        translateKey: 'nav.bankMenu.bankMenu',
        icon: 'bankMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'bankMenu.add',
                path: '/bank/add',
                title: 'Ajouter Bank',
                translateKey: 'nav.bankMenu.add',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["agent_immobilier", "admin",  'super_manager'],
                subMenu: [],
            },
            {
                key: 'bankMenu.show',
                path: '/bank/show',
                title: 'Mes Banks',
                translateKey: 'nav.bankMenu.show',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["agent_immobilier", "admin", 'super_manager'],
                subMenu: [],
            },
            {
                key: 'bankMenu.current',
                path: '/bank/approval',
                title: 'Banks Encours',
                translateKey: 'nav.bankMenu.current',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin", "coordonator", "assist_coordonator","manager", "assist_manager", 'super_manager'],
                subMenu: [],
            },
            {
                key: 'bankMenu.icurrent',
                path: '/bank/inactive',
                title: 'Banks Inactives',
                translateKey: 'nav.bankMenu.icurrent',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin", "coordonator", "assist_coordonator","manager", "assist_manager", 'super_manager'],
                subMenu: [],
            },
            {
                key: 'bankMenu.vendor',
                path: '/bank/vendor',
                title: 'Vendor Management',
                translateKey: 'nav.bankMenu.vendor',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin", "vendor_management", 'super_manager', 'super_manager'],
                subMenu: [],
            },
            {
                key: 'bankMenu.report',
                path: '/report',
                title: 'Report',
                translateKey: 'nav.bankMenu.report',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin",'super_manager', "coordonator", "assist_coordonator","manager", "assist_manager", 'super_manager'],
                subMenu: [],
            }
        ],
    },
    {
        key: 'proprioMenu',
        path: '',
        title: 'Landlord',
        translateKey: 'nav.proprioMenu.proprio',
        icon: 'proprioMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'proprioMenu.add',
                path: '/proprio/add',
                title: 'Add Landlord',
                translateKey: 'nav.proprioMenu.add',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'proprioMenu.myEntity',
                path: '/proprio/myEntity',
                title: 'Mes Entités',
                translateKey: 'nav.proprioMenu.myEntity',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'proprioMenu.show',
                path: '/proprio/show',
                title: 'Entité',
                translateKey: 'nav.proprioMenu.show',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ["admin"],
                subMenu: [],
            },
        ],
    },
    {
        key: 'configMenu',
        path: '',
        title: 'Configuration',
        translateKey: 'nav.configMenu.config',
        icon: 'configMenu',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [],
        subMenu: [
            {
                key: 'configMenu.profil',
                path: '/proprio/add',
                title: 'Add Landlord',
                translateKey: 'nav.configMenu.profil',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
            {
                key: 'configMenu.password',
                path: '/proprio/show',
                title: 'Mot de Passe',
                translateKey: 'nav.configMenu.password',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
